"""ObjectStore port (docs/connectors/object-storage.md).

Public identifiers are internal ``asset_id`` values. Bucket keys, versions and
ETags stay inside adapter-owned opaque ``version_ref`` strings. An ETag is
never treated as a SHA-256 digest: :meth:`ObjectStore.promote_verified_input`
hashes the bytes it copies.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import datetime
from typing import Protocol

from .base import CallContext, CapabilityProfile, InvalidInput, require_opaque_id, require_utc

PORT = "ObjectStore"

# Capability names.
PRESIGNED_PUT = "presigned_put"
ENFORCE_MAX_BYTES_AT_UPLOAD = "enforce_max_bytes_at_upload"
PROVIDER_SHA256_CHECKSUM = "provider_sha256_checksum"
IMMUTABLE_VERSIONS = "immutable_versions"
SERVER_SIDE_COPY = "server_side_copy"
DOWNLOAD_TICKETS = "download_tickets"
HARD_DELETE_VERSIONS = "hard_delete_versions"

_SHA256 = re.compile(r"^[0-9a-f]{64}$")
_MEDIA = re.compile(r"^[a-z]+/[a-z0-9.+-]{1,64}$")


def require_sha256(value: object, name: str) -> str:
    if not isinstance(value, str) or not _SHA256.match(value):
        raise InvalidInput("invalid_sha256", detail=name)
    return value


@dataclass(frozen=True)
class UploadPolicy:
    allowed_media_types: frozenset[str]
    max_bytes: int
    expires_in_s: int

    def __post_init__(self) -> None:
        if not self.allowed_media_types or any(not _MEDIA.match(m) for m in self.allowed_media_types):
            raise InvalidInput("invalid_upload_policy", detail="allowed_media_types")
        if type(self.max_bytes) is not int or not 0 < self.max_bytes <= 64 * 1024 * 1024:
            raise InvalidInput("invalid_upload_policy", detail="max_bytes")
        if type(self.expires_in_s) is not int or not 0 < self.expires_in_s <= 3600:
            raise InvalidInput("invalid_upload_policy", detail="expires_in_s")


@dataclass(frozen=True)
class UploadTicket:
    """A short-lived bearer capability for one upload slot (not one-use unless the
    profile says so)."""

    upload_id: str
    asset_id: str
    method: str
    url: str
    expires_at: datetime
    max_bytes: int

    def __repr__(self) -> str:  # never print the bearer URL
        return f"UploadTicket(upload_id={self.upload_id!r}, asset_id={self.asset_id!r})"


@dataclass(frozen=True)
class UploadInspection:
    upload_id: str
    present: bool
    size_bytes: int | None
    provider_sha256: str | None
    version_ref: str | None


@dataclass(frozen=True)
class StoredObject:
    """An immutable, verified object version."""

    asset_id: str
    version_ref: str
    sha256: str
    size_bytes: int
    media_type: str

    def __post_init__(self) -> None:
        require_opaque_id(self.asset_id, "asset_id")
        require_sha256(self.sha256, "sha256")
        if type(self.size_bytes) is not int or self.size_bytes < 0:
            raise InvalidInput("invalid_size", detail="size_bytes")


@dataclass(frozen=True)
class DownloadTicket:
    url: str
    expires_at: datetime

    def __post_init__(self) -> None:
        require_utc(self.expires_at, "expires_at")

    def __repr__(self) -> str:
        return "DownloadTicket(<redacted>)"


@dataclass(frozen=True)
class DeletionReceipt:
    asset_id: str
    versions_deleted: int
    complete: bool


class ObjectStore(Protocol):
    profile: CapabilityProfile

    def issue_upload_ticket(self, asset_id: str, media_type: str, policy: UploadPolicy,
                            ctx: CallContext) -> UploadTicket: ...

    def inspect_upload(self, upload_id: str, ctx: CallContext) -> UploadInspection: ...

    def promote_verified_input(self, upload_id: str, expected_sha256: str,
                               ctx: CallContext) -> StoredObject:
        """Copy current upload bytes to an internal immutable key after hashing them.

        Raises ``Conflict`` if the copied bytes do not hash to ``expected_sha256``
        (for example an overwrite after inspection).
        """
        ...

    def read_object(self, stored: StoredObject, ctx: CallContext) -> bytes:
        """Read one verified version. The application authorizes before calling."""
        ...

    def issue_download_ticket(self, stored: StoredObject, expires_in_s: int,
                              ctx: CallContext) -> DownloadTicket: ...

    def write_derivative(self, asset_id: str, parent: StoredObject, data: bytes, media_type: str,
                         ctx: CallContext) -> StoredObject:
        """Store server-generated bytes (crop, thumbnail, export) under an
        application-issued ``asset_id``; lineage to ``parent`` is recorded by the
        application."""
        ...

    def delete_asset_versions(self, asset_id: str, ctx: CallContext) -> DeletionReceipt: ...

    def verify_deletion(self, asset_id: str, ctx: CallContext) -> bool:
        """True only when no version of the asset remains readable."""
        ...
