#!/usr/bin/env python3
"""Generate/check source-backed documentation. Standard library, no provider/network calls.

Only --write changes the four explicitly generated reference pages. --check never
executes a Markdown code fence or imports the runtime application. Frozen research
is excluded from link normalization, not from its own integrity validation.
"""
from __future__ import annotations

import argparse
import ast
import importlib.util
import json
from pathlib import Path
import re
import subprocess
import sys
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
GENERATED = (
    "docs/reference/api-routes.md",
    "docs/reference/environment-matrix.md",
    "docs/reference/command-inventory.md",
    "docs/reference/component-index.md",
)
FROZEN = ("research/graphology/foundations-v0.1/",)
IGNORED_PARTS = {".git", "node_modules", ".venv", ".expo", ".next", "__pycache__", ".handover-payload"}
METHODS = {"get", "post", "put", "patch", "delete", "options", "head"}


def text(root: Path, rel: str) -> str:
    return (root / rel).read_text(encoding="utf-8")


def cell(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def link(rel: str, label: str | None = None) -> str:
    return f"[{label or rel}](../../{rel})"


def header(title: str) -> list[str]:
    return [f"# {title}", "", "<!-- GENERATED by tools/documentation.py; edit sources, then use --write. -->", "",
            "[Documentation home](../README.md) · [Generation policy](../documentation-policy.md)", ""]


def routes(source: str) -> tuple[list[dict[str, Any]], list[ast.ClassDef]]:
    tree = ast.parse(source)
    found: list[dict[str, Any]] = []
    classes = [n for n in tree.body if isinstance(n, ast.ClassDef)
               and (n.name.endswith("Body") or n.name == "_Strict")]
    for node in ast.walk(tree):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        for decorator in node.decorator_list:
            if not (isinstance(decorator, ast.Call) and isinstance(decorator.func, ast.Attribute)
                    and isinstance(decorator.func.value, ast.Name) and decorator.func.value.id == "app"
                    and decorator.func.attr in METHODS):
                continue
            if not decorator.args or not isinstance(decorator.args[0], ast.Constant) or not isinstance(decorator.args[0].value, str):
                raise ValueError("API documentation requires a reviewed literal route")
            path = decorator.args[0].value
            keywords = {k.arg: k.value for k in decorator.keywords}
            status = ast.literal_eval(keywords["status_code"]) if "status_code" in keywords else 200
            defaults = node.args.defaults + [d for d in node.args.kw_defaults if d is not None]
            principal = any(isinstance(d, ast.Call) and isinstance(d.func, ast.Name) and d.func.id == "Depends"
                            and any(isinstance(a, ast.Name) and a.id == "principal" for a in d.args) for d in defaults)
            request_models = [ast.unparse(a.annotation) for a in [*node.args.args, *node.args.kwonlyargs]
                              if a.annotation is not None and ast.unparse(a.annotation).endswith("Body")]
            found.append({"method": decorator.func.attr.upper(), "path": path, "status": status,
                          "handler": node.name, "line": node.lineno, "principal": principal,
                          "models": request_models, "returns": ast.unparse(node.returns) if node.returns else "unspecified",
                          "summary": (ast.get_docstring(node) or "").replace("\n", " ")})
    keys = [(r["method"], r["path"]) for r in found]
    if len(keys) != len(set(keys)):
        raise ValueError("duplicate literal API route; review before documenting")
    return sorted(found, key=lambda r: (r["path"], r["method"])), classes


def render_api(root: Path) -> str:
    records, classes = routes(text(root, "apps/api/princess_api/app.py"))
    out = header("Current API routes and request models")
    out += ["Source: " + link("apps/api/princess_api/app.py") + ". See [API semantics](api.md) for authorization, errors and operation-specific retry behavior.", "",
            "This is a static source inventory, not a claim that every route is enabled. Conditional development routes remain development-only. A direct principal dependency is only the first authorization layer; handler/use-case checks still apply. Default status is the decorator default, not every possible response status.", "",
            "| Method | Path | Default status | Direct principal dependency | Request model | Handler/source |",
            "|---|---|---:|---|---|---|"]
    for r in records:
        where = f"../../apps/api/princess_api/app.py#L{r['line']}"
        out.append(f"| {r['method']} | `{r['path']}` | {r['status']} | {'yes' if r['principal'] else 'no; inspect handler'} | {', '.join(r['models']) or 'parameters/raw/no body'} | [{r['handler']}]({where}) |")
    out += ["", "## Request model fields", "",
            "Types/default expressions below are source-derived Python declarations, not a parallel wire schema. `_Strict` rejects extra fields; other model configuration and custom request validation remain in the linked source. Response annotations alone do not fully specify response bodies; consult the handler, product schemas and client guards.", ""]
    for cls in classes:
        out += [f"### {cls.name}", "", "| Field | Source type | Source default/constraint expression |", "|---|---|---|"]
        for node in cls.body:
            if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
                default = ast.unparse(node.value) if node.value else "required"
                out.append(f"| `{node.target.id}` | `{cell(ast.unparse(node.annotation))}` | `{cell(default)}` |")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def render_environments(root: Path) -> str:
    out = header("Declared environment and component matrix")
    out += ["Generated from `infra/environments/*.json`. These declarations describe target modes and boundaries; runtime preflight/composition may reject unimplemented modes. A declaration is not provider approval, deployment evidence or a secret value. Read [configuration](configuration.md) and [provider decisions](../roadmap/19-provider-decision-register.md).", ""]
    for path in sorted((root / "infra/environments").glob("*.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(data, dict) or "providers" not in data or "components" not in data:
            continue
        rel = path.relative_to(root).as_posix()
        out += [f"## {data['environment']}", "", f"Source: {link(rel)}. Database declaration: `{cell(data.get('database', {}).get('name', 'not declared'))}`.", "",
                "| Provider port | Declared mode |", "|---|---|"]
        out += [f"| `{cell(k)}` | `{cell(v)}` |" for k, v in sorted(data["providers"].items())]
        out += ["", "| Switch | Declared value |", "|---|---|"]
        out += [f"| `{cell(k)}` | `{str(v).lower()}` |" for k, v in sorted(data.get("kill_switches", {}).items())]
        out += ["", "| Component | Permitted secret names (not values) | Declared egress |", "|---|---|---|"]
        for name, component in sorted(data["components"].items()):
            out.append(f"| `{name}` | {cell(', '.join(component.get('secrets', []))) or 'none'} | {cell(', '.join(component.get('egress', []))) or 'none'} |")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def render_commands(root: Path) -> str:
    out = header("Package, tool and migration inventory")
    out += ["Inventory only: consult [command safety](commands.md) and [testing](../development/testing.md) before execution. A file may be a library or a destructive/protected operator tool. This generator does not execute it or assert every tool supports `--help`.", "", "## Package scripts", "",
            "| Package / manifest | Script | Source command |", "|---|---|---|"]
    manifests = [root / "package.json", *sorted((root / "apps").glob("*/package.json")), *sorted((root / "packages").glob("*/package.json"))]
    for path in manifests:
        if not path.is_file():
            continue
        data = json.loads(path.read_text(encoding="utf-8"))
        for name, command in sorted(data.get("scripts", {}).items()):
            out.append(f"| {link(path.relative_to(root).as_posix(), cell(data.get('name', 'workspace')))} | `{cell(name)}` | `{cell(command)}` |")
    out += ["", "## Python and shell tool entry files", "", "| Path | Source description |", "|---|---|"]
    paths = [*sorted((root / "tools").glob("*.py")), *sorted((root / "tools").glob("*.sh")),
             *sorted((root / "apps/workers").glob("*/run_worker.py")), root / "apps/api/princess_api/ops.py"]
    for path in paths:
        body = path.read_text(encoding="utf-8")
        description = "Read source and owning guide before running"
        if path.suffix == ".py":
            doc = ast.get_docstring(ast.parse(body))
            if doc:
                description = doc.splitlines()[0]
        else:
            comments = [line.lstrip("# ") for line in body.splitlines() if line.startswith("# ")]
            if comments:
                description = comments[0]
        out.append(f"| {link(path.relative_to(root).as_posix())} | {cell(description)} |")
    out += ["", "## Migration inventory", "", "Apply via the reviewed migration command, not by executing revision files. See [migrations](../../migrations/README.md).", "",
            "| File | Declared revision | Declared predecessor |", "|---|---|---|"]
    for path in sorted((root / "migrations/versions").glob("*.py")):
        values = {}
        for node in ast.parse(path.read_text(encoding="utf-8")).body:
            if isinstance(node, ast.Assign):
                targets, value = node.targets, node.value
            elif isinstance(node, ast.AnnAssign):
                targets, value = [node.target], node.value
            else:
                continue
            for target in targets:
                if isinstance(target, ast.Name) and target.id in {"revision", "down_revision"} and value is not None:
                    try:
                        values[target.id] = ast.literal_eval(value)
                    except (ValueError, TypeError):
                        values[target.id] = "inspect source"
        out.append(f"| {link(path.relative_to(root).as_posix())} | `{cell(values.get('revision', 'inspect source'))}` | `{cell(values.get('down_revision'))}` |")
    out += ["", "## Workflows", "", "Names and paths are source inventory, not current run status. Core CI is generated by its own reviewed policy.", "", "| Workflow file | Name |", "|---|---|"]
    for path in sorted((root / ".github/workflows").glob("*.yml")):
        match = re.search(r"^name:\s*(.+)$", path.read_text(encoding="utf-8"), re.MULTILINE)
        out.append(f"| {link(path.relative_to(root).as_posix())} | {cell(match.group(1) if match else 'unnamed')} |")
    return "\n".join(out).rstrip() + "\n"


def markdown_files(root: Path) -> list[Path]:
    try:
        result = subprocess.run(["git", "ls-files", "--cached", "--others", "--exclude-standard", "--", "*.md"],
                                cwd=root, check=True, text=True, capture_output=True)
        candidates = [root / p for p in result.stdout.splitlines()]
    except (OSError, subprocess.CalledProcessError):
        candidates = list(root.rglob("*.md"))
    return sorted({p for p in candidates if p.is_file() and not p.is_symlink()
                   and not IGNORED_PARTS.intersection(p.relative_to(root).parts)
                   and not any(p.relative_to(root).as_posix().startswith(prefix) for prefix in FROZEN)})


def render_components(root: Path) -> str:
    out = header("Component and specialist navigation")
    out += ["All maintained README entry pages discovered in the source tree are listed below. Generated/build directories and the immutable research snapshot are excluded from this maintained-navigation list. Frozen research is reached through its current wrapper. A README's existence is not feature completion.", "", "| Entry page | Title |", "|---|---|"]
    for path in markdown_files(root):
        if path.name.lower() != "readme.md":
            continue
        body = path.read_text(encoding="utf-8")
        title = next((line.lstrip("# ") for line in body.splitlines() if line.startswith("# ")), path.parent.name)
        out.append(f"| {link(path.relative_to(root).as_posix())} | {cell(title)} |")
    out += ["", "## Retained license-text candidates", "",
            "These paths locate license records; filename discovery is not a legal clearance decision. Read [third-party notices](../../THIRD_PARTY_NOTICES.md) and the actual source/rights record. Project licensing, data, model weights and fonts remain separate.", ""]
    licenses = [p for p in (root / "provenance").rglob("*") if p.is_file()
                and any(token in p.name.lower() for token in ("license", "licence", "copying"))]
    if not licenses:
        out.append("No standalone retained license-text path was discovered under provenance. Review [provenance/SOURCES.md](../../provenance/SOURCES.md) and its original artifact/commit references; do not claim a license text has been delivered when it has not.")
    else:
        out += ["- " + link(p.relative_to(root).as_posix()) for p in sorted(licenses)]
    return "\n".join(out).rstrip() + "\n"


def generated(root: Path) -> dict[str, str]:
    return dict(zip(GENERATED, [render_api(root), render_environments(root), render_commands(root), render_components(root)]))


def target_errors(root: Path, inventory: dict[str, Any]) -> list[str]:
    errors = []
    for rel in inventory.get("required_paths", []):
        path = (root / rel).resolve()
        if not path.is_relative_to(root.resolve()) or not path.exists():
            errors.append(f"missing/unsafe registered documentation target: {rel}")
    for rel, names in inventory.get("package_scripts", {}).items():
        try:
            scripts = json.loads(text(root, rel)).get("scripts", {})
        except (OSError, ValueError):
            errors.append(f"missing/invalid package manifest: {rel}")
            continue
        for name in names:
            if name not in scripts:
                errors.append(f"missing documented package script: {rel}:{name}")
    return errors


def link_errors(root: Path, paths: list[Path]) -> list[str]:
    spec = importlib.util.spec_from_file_location("handover_plan_links", ROOT / "docs/roadmap/plan_tools.py")
    if spec is None or spec.loader is None:
        raise ValueError("roadmap link checker missing")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.validate_links(root, paths)


def check(root: Path) -> list[str]:
    errors = []
    for rel, expected in generated(root).items():
        if not (root / rel).is_file() or text(root, rel) != expected:
            errors.append(f"generated documentation drift: {rel}; run python tools/documentation.py --write")
    inventory = json.loads(text(root, "docs/reference/inventory.json"))
    errors += target_errors(root, inventory)
    errors += link_errors(root, markdown_files(root))
    return errors


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    try:
        if args.write:
            for rel, content in generated(ROOT).items():
                (ROOT / rel).parent.mkdir(parents=True, exist_ok=True)
                (ROOT / rel).write_text(content, encoding="utf-8")
            print(f"Generated {len(GENERATED)} source-backed documentation references")
            return 0
        errors = check(ROOT)
        if errors:
            print("FAIL:\n" + "\n".join(errors), file=sys.stderr)
            return 1
        print(f"PASS: {len(markdown_files(ROOT))} maintained Markdown files, local links, generated references and registered targets")
        return 0
    except (OSError, ValueError, TypeError, KeyError, SyntaxError) as exc:
        print(f"FAIL: documentation input: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
