"""Generate CSS, TypeScript, Swift and Kotlin design tokens from one source (T10).

    python tools/generate_design_tokens.py          # write
    python tools/generate_design_tokens.py --check  # fail if generated files drift

Standard library only. The source is ``packages/design-tokens/tokens.json``;
values are drafts pending the ``design_acceptance`` gate.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "packages" / "design-tokens" / "tokens.json"
OUT = ROOT / "packages" / "design-tokens" / "generated"
HEADER = "GENERATED by tools/generate_design_tokens.py from packages/design-tokens/tokens.json; do not edit."


def _flat(prefix: str, node: dict) -> list[tuple[str, str]]:
    items: list[tuple[str, str]] = []
    for key, value in node.items():
        name = f"{prefix}-{key}"
        if isinstance(value, dict):
            items.extend(_flat(name, value))
        elif isinstance(value, str):
            items.append((name, value))
    return items


def _scalars(tokens: dict) -> list[tuple[str, str]]:
    out = []
    for group in ("font", "space", "radius", "breakpoint", "target"):
        out.extend(_flat(group, tokens[group]))
    out.extend(_flat("motion", {k: tokens["motion"][k] for k in ("duration", "easing")}))
    out.extend((f"chart-series-{i + 1}", color) for i, color in enumerate(tokens["chart"]["series"]))
    return out


def css(tokens: dict) -> str:
    light = [f"  --color-{k}: {v};" for k, v in tokens["color"]["light"].items()]
    dark = [f"  --color-{k}: {v};" for k, v in tokens["color"]["dark"].items()]
    scalars = [f"  --{k}: {v};" for k, v in _scalars(tokens)]
    reduced = [f"    --motion-duration-{k}: 0ms;" for k in tokens["motion"]["duration"]]
    return "\n".join([
        f"/* {HEADER} */",
        f"/* {tokens['version']} ({tokens['status']}) */",
        ":root {", "  color-scheme: light dark;", *light, *scalars, "}",
        "@media (prefers-color-scheme: dark) {", '  :root:not([data-theme="light"]) {',
        *["  " + line for line in dark], "  }", "}",
        ':root[data-theme="dark"] {', *dark, "}",
        "@media (prefers-reduced-motion: reduce) {", "  :root {", *reduced, "  }", "}", "",
    ])


def _camel(name: str) -> str:
    parts = re.split(r"[-_]", name)
    head = parts[0] if not parts[0][:1].isdigit() else f"n{parts[0]}"
    return head + "".join(p[:1].upper() + p[1:] for p in parts[1:])


def ts(tokens: dict) -> str:
    colors = {theme: dict(values) for theme, values in tokens["color"].items()}
    body = {"version": tokens["version"], "status": tokens["status"], "color": colors,
            "chart": {"series": tokens["chart"]["series"]}, "font": tokens["font"], "space": tokens["space"],
            "radius": tokens["radius"], "motion": {k: tokens["motion"][k] for k in ("duration", "easing")},
            "breakpoint": tokens["breakpoint"], "target": tokens["target"], "print": tokens["print"]}
    roles = " | ".join(json.dumps(k) for k in tokens["color"]["light"])
    return "\n".join([
        f"// {HEADER}",
        f"export const tokens = {json.dumps(body, indent=2, ensure_ascii=False)} as const;", "",
        f"export type ColorRole = {roles};",
        'export type Theme = "light" | "dark";', "",
        "export function color(theme: Theme, role: ColorRole): string {",
        "  return tokens.color[theme][role];", "}", "",
    ])


def _argb(hex_color: str) -> str:
    return "0xFF" + hex_color.lstrip("#").upper()


def swift(tokens: dict) -> str:
    lines = [f"// {HEADER}", "// Hex strings; SwiftUI/UIKit colour construction belongs to the T29 native foundation.",
             "public enum PrincessTokens {", f'    public static let version = "{tokens["version"]}"',
             "    public enum Light {"]
    lines += [f'        public static let {_camel(k)} = "{v}"' for k, v in tokens["color"]["light"].items()]
    lines += ["    }", "    public enum Dark {"]
    lines += [f'        public static let {_camel(k)} = "{v}"' for k, v in tokens["color"]["dark"].items()]
    lines += ["    }", "    public enum Space {"]
    lines += [f"        public static let {_camel('s' + k)}: Double = {v.replace('px', '') or '0'}"
              for k, v in tokens["space"].items()]
    lines += ["    }", "    public enum Motion {"]
    lines += [f"        public static let {k}Seconds: Double = {int(v.replace('ms', '')) / 1000}"
              for k, v in tokens["motion"]["duration"].items()]
    lines += ["    }", f"    public static let minTouchPoints: Double = {tokens['target']['min-touch'].replace('px', '')}",
              "}", ""]
    return "\n".join(lines)


def kotlin(tokens: dict) -> str:
    lines = [f"// {HEADER}", "package se.princess.tokens", "", "object PrincessTokens {",
             f'    const val VERSION = "{tokens["version"]}"', "", "    object Light {"]
    lines += [f"        const val {k.upper().replace('-', '_')}: Long = {_argb(v)}"
              for k, v in tokens["color"]["light"].items()]
    lines += ["    }", "", "    object Dark {"]
    lines += [f"        const val {k.upper().replace('-', '_')}: Long = {_argb(v)}"
              for k, v in tokens["color"]["dark"].items()]
    lines += ["    }", "", "    object SpaceDp {"]
    lines += [f"        const val S{k}: Int = {v.replace('px', '') or '0'}" for k, v in tokens["space"].items()]
    lines += ["    }", "", "    object MotionMs {"]
    lines += [f"        const val {k.upper()}: Long = {v.replace('ms', '')}" for k, v in tokens["motion"]["duration"].items()]
    lines += ["    }", "", f"    const val MIN_TOUCH_DP: Int = {tokens['target']['min-touch'].replace('px', '')}", "}", ""]
    return "\n".join(lines)


def outputs() -> dict[Path, str]:
    tokens = json.loads(SOURCE.read_text(encoding="utf-8"))
    return {OUT / "tokens.css": css(tokens), OUT / "tokens.ts": ts(tokens), OUT / "PrincessTokens.swift": swift(tokens),
            OUT / "PrincessTokens.kt": kotlin(tokens)}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    stale = []
    for path, content in outputs().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(path.relative_to(ROOT).as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if stale:
        print("stale generated design tokens: " + ", ".join(stale), file=sys.stderr)
        return 1
    print("PASS: design tokens are current" if args.check else "Generated design tokens")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
