#!/usr/bin/env python3
"""Generate all T01 product contract artifacts from reviewed JSON Schema sources."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from product_contract_common import (
    FEATURE_SOURCE, METHOD_SOURCE, PURPOSE_SOURCE, ROOT, SCHEMA_ROOT, T26_SOURCE,
    canonical_bytes, feature_authority, file_sha256, load_schemas, purpose_authority,
    resolve_method_capabilities, resolve_ref, sha256_bytes, t26_authority,
)

PY_OUT = ROOT / "src" / "princess_contracts" / "generated.py"
TS_OUT = ROOT / "packages" / "contracts" / "src" / "generated.ts"
OPENAPI_OUT = ROOT / "contracts" / "http" / "openapi-components.json"
MANIFEST_OUT = ROOT / "contracts" / "product" / "v1" / "manifest.json"
CAP_OUT = ROOT / "schema" / "method_capabilities" / "resolved.json"
CONTRACT_VERSION = "1.0.0"


def _py_name(schema_file: str, node: dict[str, Any], fragment: str = "") -> str:
    if fragment.startswith("#/$defs/"):
        return fragment.split("/")[-1]
    title = node.get("title")
    if isinstance(title, str) and title:
        return title
    stem = schema_file.removesuffix(".schema.json")
    return "".join(piece.capitalize() for piece in stem.split("-"))


def _literal(value: Any, lang: str) -> str:
    if lang == "py":
        return repr(value)
    return json.dumps(value, ensure_ascii=False)


def _type_expr(node: dict[str, Any], *, schemas: dict[str, dict[str, Any]], current: str, lang: str) -> str:
    if "$ref" in node:
        target_file, fragment, target = resolve_ref(schemas, current, node["$ref"])
        return _py_name(target_file, target, fragment)
    if "const" in node:
        value = _literal(node["const"], lang)
        return f"Literal[{value}]" if lang == "py" else value
    if "enum" in node:
        values = ", ".join(_literal(v, lang) for v in node["enum"])
        return f"Literal[{values}]" if lang == "py" else " | ".join(_literal(v, lang) for v in node["enum"])
    if "anyOf" in node:
        parts = []
        for child in node["anyOf"]:
            expr = _type_expr(child, schemas=schemas, current=current, lang=lang)
            if expr not in parts:
                parts.append(expr)
        return " | ".join(parts)
    typ = node.get("type")
    if typ == "string":
        return "str" if lang == "py" else "string"
    if typ == "integer":
        return "int" if lang == "py" else "number"
    if typ == "number":
        return "float | int" if lang == "py" else "number"
    if typ == "boolean":
        return "bool" if lang == "py" else "boolean"
    if typ == "null":
        return "None" if lang == "py" else "null"
    if typ == "array":
        item = _type_expr(node["items"], schemas=schemas, current=current, lang=lang)
        return f"list[{item}]" if lang == "py" else f"ReadonlyArray<{item}>"
    if typ == "object":
        return "dict[str, Any]" if lang == "py" else "Readonly<Record<string, unknown>>"
    return "Any" if lang == "py" else "unknown"


def _definitions(schemas: dict[str, dict[str, Any]]) -> list[tuple[str, str, dict[str, Any]]]:
    out: list[tuple[str, str, dict[str, Any]]] = []
    common = schemas.get("common.schema.json", {})
    for name, node in common.get("$defs", {}).items():
        out.append(("common.schema.json", name, node))
    for file_name in sorted(schemas):
        if file_name == "common.schema.json":
            continue
        node = schemas[file_name]
        out.append((file_name, _py_name(file_name, node), node))
    return out


def render_python(schemas: dict[str, dict[str, Any]], manifest: dict[str, Any], features: dict[str, Any], caps: dict[str, Any], t26: dict[str, Any], purposes: dict[str, Any]) -> str:
    lines = [
        '"""GENERATED by tools/generate_product_contracts.py; do not edit."""',
        "from __future__ import annotations", "", "import json as _json", "from typing import Literal, TypeAlias, TypedDict", "",
        f"CONTRACT_VERSION = {CONTRACT_VERSION!r}",
        f"CONTRACT_BUNDLE_SHA256 = {manifest['bundle_sha256']!r}",
        f"FEATURE_SCHEMA_VERSION = {features['schema_version']!r}",
        f"FEATURE_SOURCE_SHA256 = {features['source_sha256']!r}",
        f"METHOD_MANIFEST_SHA256 = {caps['manifest_sha256']!r}",
        f"T26_VERSION = {t26['version']!r}",
        f"T26_SHA256 = {t26['sha256']!r}", "",
    ]
    feature_ids = sorted(features["features"])
    purpose_ids = sorted(purposes["versions"])
    pack_ids = sorted(t26["question_packs"])
    lines += [
        "FeatureId: TypeAlias = Literal[" + ", ".join(repr(x) for x in feature_ids) + "]",
        "PurposeId: TypeAlias = Literal[" + ", ".join(repr(x) for x in purpose_ids) + "]",
        "QuestionPackId: TypeAlias = Literal[" + ", ".join(repr(x) for x in pack_ids) + "]", "",
    ]
    for current, name, node in _definitions(schemas):
        if node.get("type") == "object":
            props = node["properties"]
            entries = ", ".join(
                f"{prop!r}: {_type_expr(child, schemas=schemas, current=current, lang='py')}"
                for prop, child in props.items()
            )
            lines.append(f"{name} = TypedDict({name!r}, {{{entries}}})")
            lines.append("")
        else:
            lines.append(f"{name}: TypeAlias = {_type_expr(node, schemas=schemas, current=current, lang='py')}")
            lines.append("")
    embedded = {
        "SCHEMAS": schemas,
        "CONTRACT_MANIFEST": manifest,
        "FEATURES": features["features"],
        "METHOD_CAPABILITIES": caps,
        "T26_AUTHORITY": t26,
        "PURPOSE_AUTHORITY": purposes,
    }
    for name, value in embedded.items():
        payload = json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"), allow_nan=False)
        lines.append(f"{name} = _json.loads({json.dumps(payload, ensure_ascii=False)})")
    lines.append("")
    return "\n".join(lines)


def render_ts(schemas: dict[str, dict[str, Any]], manifest: dict[str, Any], features: dict[str, Any], t26: dict[str, Any], purposes: dict[str, Any]) -> str:
    lines = ["// GENERATED by tools/generate_product_contracts.py; do not edit.", f"export const CONTRACT_VERSION = {json.dumps(CONTRACT_VERSION)} as const;", f"export const CONTRACT_BUNDLE_SHA256 = {json.dumps(manifest['bundle_sha256'])} as const;", ""]
    lines += [
        "export type FeatureId = " + " | ".join(json.dumps(x) for x in sorted(features["features"])) + ";",
        "export type PurposeId = " + " | ".join(json.dumps(x) for x in sorted(purposes["versions"])) + ";",
        "export type QuestionPackId = " + " | ".join(json.dumps(x) for x in sorted(t26["question_packs"])) + ";", "",
    ]
    for current, name, node in _definitions(schemas):
        if node.get("type") == "object":
            lines.append(f"export interface {name} {{")
            for prop, child in node["properties"].items():
                lines.append(f"  readonly {prop}: {_type_expr(child, schemas=schemas, current=current, lang='ts')};")
            lines += ["}", ""]
        else:
            lines += [f"export type {name} = {_type_expr(node, schemas=schemas, current=current, lang='ts')};", ""]
    return "\n".join(lines)


def _rewrite_openapi(node: Any, *, current_file: str, schemas: dict[str, dict[str, Any]]) -> Any:
    if isinstance(node, list):
        return [_rewrite_openapi(x, current_file=current_file, schemas=schemas) for x in node]
    if not isinstance(node, dict):
        return node
    if "$ref" in node:
        file_name, fragment, target = resolve_ref(schemas, current_file, node["$ref"])
        return {"$ref": f"#/components/schemas/{_py_name(file_name, target, fragment)}"}
    out = {}
    for key, value in node.items():
        if key in {"$schema", "$id", "$defs"}:
            continue
        out[key] = _rewrite_openapi(value, current_file=current_file, schemas=schemas)
    return out


def render_openapi(schemas: dict[str, dict[str, Any]]) -> dict[str, Any]:
    components: dict[str, Any] = {}
    common = schemas["common.schema.json"]
    for name, node in common["$defs"].items():
        components[name] = _rewrite_openapi(node, current_file="common.schema.json", schemas=schemas)
    for file_name in sorted(schemas):
        if file_name == "common.schema.json":
            continue
        node = schemas[file_name]
        components[_py_name(file_name, node)] = _rewrite_openapi(node, current_file=file_name, schemas=schemas)
    return {"openapi":"3.1.0","info":{"title":"Princess product contract components","version":CONTRACT_VERSION},"paths":{},"components":{"schemas":components}}


def build() -> dict[Path, str]:
    schemas = load_schemas()
    features = feature_authority()
    t26 = t26_authority()
    purposes = purpose_authority()
    caps = resolve_method_capabilities(features["features"])
    schema_entries = []
    root_schemas = {}
    for path in sorted(SCHEMA_ROOT.glob("*.schema.json")):
        node = schemas[path.name]
        entry = {"path": f"schemas/{path.name}", "schema_id": path.name, "sha256": file_sha256(path)}
        if path.name != "common.schema.json":
            entry["title"] = node["title"]
            root_schemas[node["title"]] = path.name
        schema_entries.append(entry)
    manifest = {
        "contract_id":"princess-product-contracts", "contract_version":CONTRACT_VERSION,
        "canonicalization":"utf8-json-sort-keys-no-nonfinite-v1", "schemas":schema_entries,
        "root_schemas":dict(sorted(root_schemas.items())),
        "authorities":{
            "feature_database":{"path":str(FEATURE_SOURCE.relative_to(ROOT)),"sha256":features["source_sha256"],"version":features["schema_version"]},
            "feature_runtime_contract":{"path":"src/princess_graphology/_feature_contract.json","sha256":features["runtime_sha256"]},
            "method_capabilities":{"path":str(METHOD_SOURCE.relative_to(ROOT)),"sha256":caps["source_sha256"],"resolved_sha256":caps["manifest_sha256"]},
            "premium_interpretation_database":{"path":str(T26_SOURCE.relative_to(ROOT)),"sha256":t26["sha256"],"version":t26["version"]},
            "consent_purpose_registry":{"path":str(PURPOSE_SOURCE.relative_to(ROOT)),"sha256":purposes["sha256"]},
        }
    }
    manifest["bundle_sha256"] = sha256_bytes(canonical_bytes(manifest))
    return {
        MANIFEST_OUT: json.dumps(manifest,indent=2,ensure_ascii=False,sort_keys=True)+"\n",
        CAP_OUT: json.dumps(caps,indent=2,ensure_ascii=False,sort_keys=True)+"\n",
        PY_OUT: render_python(schemas,manifest,features,caps,t26,purposes),
        TS_OUT: render_ts(schemas,manifest,features,t26,purposes),
        OPENAPI_OUT: json.dumps(render_openapi(schemas),indent=2,ensure_ascii=False,sort_keys=True)+"\n",
    }


def main() -> int:
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check",action="store_true")
    args=parser.parse_args()
    outputs=build()
    stale=[]
    for path, content in outputs.items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True,exist_ok=True)
            path.write_text(content,encoding="utf-8")
    if stale:
        print("FAIL stale generated product contracts: " + ", ".join(stale))
        return 1
    if args.check:
        print(f"PASS product contract generation: {len(outputs)} generated artifacts")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
