#!/usr/bin/env python3
"""Render the complete, mandatory CI workflow from strictly typed reviewed targets.

The renderer is reviewed executable policy, not an editable YAML template. A
workflow changed outside it never counts as interpreter coverage. This does not
replace branch protection or review of changes to the verifier/renderer itself.
"""
from __future__ import annotations

import argparse
import json
import re
import stat
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def _pairs(items):
    result = {}
    for key, value in items:
        if key in result:
            raise ValueError(f"duplicate target JSON key {key!r}")
        result[key] = value
    return result


def require_regular_file(path: Path) -> None:
    """Repository policy must be a regular file, never a symlink or special file.

    The checkout is trusted not to be concurrently rewritten while CI runs.
    This is a configuration consistency check, not an OS sandbox.
    """
    path = path.absolute()
    for component in (path, *path.parents):
        if component.is_symlink():
            raise ValueError(f"symlink is not reviewed policy: {component.name}")
    if not stat.S_ISREG(path.stat().st_mode):
        raise ValueError(f"not a regular reviewed file: {path.name}")


def load_targets(path: Path) -> list[dict[str, str]]:
    require_regular_file(path)
    if path.stat().st_size > 65536:
        raise ValueError("target configuration exceeds 64 KiB")
    try:
        data = json.loads(path.read_text(encoding="utf-8"), object_pairs_hook=_pairs)
    except RecursionError as exc:
        raise ValueError("target configuration is nested too deeply") from exc
    if not isinstance(data, dict) or set(data) != {"version", "targets"} or type(data["version"]) is not int or data["version"] != 1:
        raise ValueError("expected ci-targets version 1 and targets only")
    targets = data["targets"]
    if not isinstance(targets, list) or not 1 <= len(targets) <= 32:
        raise ValueError("expected 1..32 reviewed targets")
    seen = set()
    for target in targets:
        if not isinstance(target, dict) or set(target) != {"python", "manifest", "lock", "system", "machine"}:
            raise ValueError("target fields must be python, manifest, lock, system, machine")
        if not all(type(v) is str for v in target.values()) or not re.fullmatch(r"3\.(0|[1-9][0-9]?)", target["python"]):
            raise ValueError("target python must be a whole-minor string")
        if target["python"] in seen:
            raise ValueError("duplicate target interpreter")
        seen.add(target["python"])
        stem = "requirements/ci-py" + target["python"].replace(".", "")
        if target["manifest"] != stem + ".txt" or target["lock"] != stem + ".lock":
            raise ValueError("target must use its canonical manifest/lock path")
        if (target["system"], target["machine"]) != ("Linux", "x86_64"):
            raise ValueError("the reviewed runner supports Linux x86_64 only")
    return sorted(targets, key=lambda t: tuple(map(int, t["python"].split("."))))


WORKFLOW_PREFIX = '# Generated by tools/render_ci_workflow.py; edit reviewed policy there, not this file.\nname: CI\n\non:\n  push:\n    branches: [main, feat/schema-contract-core-metrics]\n  pull_request:\n\npermissions:\n  contents: read\n\njobs:\n  test:\n    runs-on: ubuntu-24.04\n    strategy:\n      fail-fast: false\n      matrix:\n        include:\n'

WORKFLOW_SUFFIX = '    env:\n      PIP_DISABLE_PIP_VERSION_CHECK: \'1\'\n      PIP_NO_INPUT: \'1\'\n    steps:\n      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1\n      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0\n        with:\n          python-version: ${{ matrix.python }}\n\n      - name: Verify canonical mandatory workflow\n        run: python tools/render_ci_workflow.py --check\n\n      - name: Download reviewed dependency artifacts\n        shell: bash\n        run: |\n          mkdir -p "$RUNNER_TEMP/ci-wheelhouse"\n          python -m pip download \\\n            --require-hashes \\\n            --only-binary=:all: \\\n            --no-deps \\\n            --dest "$RUNNER_TEMP/ci-wheelhouse" \\\n            -r "${{ matrix.lock }}"\n\n      - name: Install reviewed dependency artifacts\n        shell: bash\n        run: |\n          python -m pip install \\\n            --require-hashes \\\n            --only-binary=:all: \\\n            --no-index \\\n            --no-deps \\\n            --force-reinstall \\\n            --find-links "$RUNNER_TEMP/ci-wheelhouse" \\\n            -r "${{ matrix.lock }}"\n\n      - name: Verify build toolchain\n        run: |\n          python -m pip --version\n          python -c \'import setuptools, wheel; assert setuptools.__version__ == "84.0.0"; assert wheel.__version__ == "0.48.0"\'\n\n      - name: Verify project dependency policy and closed locked graph\n        run: >-\n          python tools/verify_project_dependency_policy.py\n          --manifest "${{ matrix.manifest }}"\n          --extra dev\n          --lock "${{ matrix.lock }}"\n          --wheelhouse "$RUNNER_TEMP/ci-wheelhouse"\n          --root pip\n\n      - name: Verify backend-reported build requirements\n        run: >-\n          python tools/verify_project_dependency_policy.py\n          --manifest "${{ matrix.manifest }}"\n          --extra dev\n          --backend-requirements\n\n      - name: Install local project without dependency resolution\n        shell: bash\n        run: |\n          python -m pip install \\\n            --no-index \\\n            --no-deps \\\n            --no-build-isolation \\\n            -e \'.[dev]\'\n\n      - name: Verify exact reviewed environment\n        run: >-\n          python tools/verify_ci_lock.py\n          "${{ matrix.lock }}"\n          --manifest "${{ matrix.manifest }}"\n          --allow "special-little-princess-graphology==0.1.0"\n\n      - run: python -m pip check\n      - name: Show resolved dependencies\n        run: python -m pip freeze --all\n      - run: python tools/generate_feature_contract.py --check\n      - run: python tools/compile_premium_interpretation_db.py --check\n      - run: python tools/generate_product_contracts.py --check\n      - run: python tools/generate_presentation_content.py --check\n      - run: python tools/validate_product_contracts.py\n      - run: python tools/validate_graphology_integrity.py\n      - run: python tools/validate_graphology_ontology.py\n      - run: python tools/validate_graphology_selector_foundation.py\n      - run: python tools/validate_graphology_traditional_rules.py\n      - run: python tools/validate_graphology_database.py\n      - run: python tools/validate_consent_protocol.py\n      - run: python -m compileall -q src\n      - run: ruff check src tests tools\n      - run: python -m pytest -q\n      - name: Exercise consent invariant fault-injection controls\n        run: python tools/test_contract_faults.py\n      - name: Exercise product-contract fault-injection controls\n        run: python tools/test_product_contract_faults.py\n      - name: Verify graphology research import\n        run: python tools/check_graphology_research.py\n      - name: Run graphology research regression tests\n        run: python tools/test_graphology_research.py\n      - name: Build wheel offline\n        run: python -m pip wheel . --no-deps --no-build-isolation --no-index --wheel-dir dist\n      - name: Verify installed wheel outside checkout\n        shell: bash\n        run: |\n          python -m pip install --no-index --no-deps --target "$RUNNER_TEMP/princess-installed" dist/*.whl\n          cd "$RUNNER_TEMP"\n          PYTHONPATH="$RUNNER_TEMP/princess-installed" python -c \'import json; import numpy as np; from princess_contracts import contract_identity, free_feature_ids; from princess_graphology import GraphologyEngine; from princess_graphology.schema_validation import load_contract; assert load_contract()["feature_count"] == 272; assert contract_identity()[0] == "1.0.0"; assert len(free_feature_ids()) == 64; assert len(json.loads(GraphologyEngine().analyze(np.full((40, 60), 255, np.uint8)).to_json())["measurements"]) == 64\'\n'

def render_workflow(targets: list[dict[str, str]]) -> str:
    matrix = "".join(
        f"          - python: '{target['python']}'\n"
        f"            manifest: {target['manifest']}\n"
        f"            lock: {target['lock']}\n" for target in targets
    )
    return WORKFLOW_PREFIX + matrix + WORKFLOW_SUFFIX


def verified_targets(root: Path, workflow: Path | None = None) -> list[dict[str, str]]:
    targets = load_targets(root / "requirements" / "ci-targets.json")
    workflow = workflow or root / ".github" / "workflows" / "ci.yml"
    require_regular_file(workflow)
    if workflow.stat().st_size > 131072:
        raise ValueError("workflow exceeds 128 KiB")
    if workflow.read_bytes() != render_workflow(targets).encode("utf-8"):
        raise ValueError("workflow differs from the canonical mandatory-job policy; regenerate and review it")
    return targets


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    path = ROOT / ".github" / "workflows" / "ci.yml"
    try:
        if args.check:
            verified_targets(ROOT, path)
            print("PASS canonical mandatory CI workflow")
        else:
            path.write_bytes(render_workflow(load_targets(ROOT / "requirements" / "ci-targets.json")).encode("utf-8"))
    except (OSError, ValueError, TypeError) as exc:
        print(f"FAIL {exc}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
